import { v4 as uuidv4 } from 'uuid';
import type { TradingPlannerInput, TradingPlan, PlannerOptions, ExecutionResult, OrderExecutor } from './types';

const DEFAULT_OPTIONS: PlannerOptions = {
  riskTolerance: 'moderate',
  maxCapitalAllocation: 10000,
  maxRiskPerTrade: 0.02,
  preferredTimeframe: '1h',
  strategyBias: 'neutral',
  executionMode: 'manual',
  manualApproval: true,
};

export class TradingPlanner {
  constructor(private executor?: OrderExecutor) {}

  createPlan(input: TradingPlannerInput): TradingPlan {
    const options = { ...DEFAULT_OPTIONS, ...input.options };
    const marketCondition = this.evaluateMarketCondition(input.marketData);
    const trendBias = this.selectTrendBias(input.marketData);
    const timeframe = this.selectTimeframe(input.marketData, options);
    const strategy = this.selectStrategy(input.marketData, options, marketCondition);
    const risk = this.selectRisk(options, marketCondition, trendBias);
    const priceTargets = this.generatePriceTargets(input.marketData, strategy, risk, timeframe);
    const probability = this.estimateProbability(input.marketData, strategy, risk, priceTargets);
    const sizing = this.calculatePositionSizing(input.capital, risk, priceTargets, probability, options);
    const execution = this.buildExecutionPlan(priceTargets, options);

    const plan: TradingPlan = {
      planId: uuidv4(),
      createdAt: Date.now(),
      symbol: input.marketData.symbol,
      marketCondition,
      trendBias,
      strategy,
      timeframe,
      risk,
      sizing,
      priceTargets,
      probability,
      execution,
      manualApproval: options.manualApproval ?? true,
      autoExecution: options.executionMode === 'automatic',
      status: options.manualApproval ? 'pending' : 'approved',
      commentary: 'Autonomous trading plan generated by TradingPlanner.',
    };

    return plan;
  }

  async approvePlan(plan: TradingPlan): Promise<TradingPlan> {
    if (plan.status !== 'pending') {
      throw new Error('Plan is not pending approval');
    }
    return { ...plan, status: 'approved' };
  }

  async rejectPlan(plan: TradingPlan, reason: string): Promise<TradingPlan> {
    return { ...plan, status: 'rejected', commentary: reason };
  }

  async executePlan(plan: TradingPlan): Promise<ExecutionResult> {
    if (!this.executor) {
      throw new Error('Order executor is not configured');
    }
    if (plan.status !== 'approved') {
      throw new Error('Plan must be approved before execution');
    }
    if (plan.execution.executionMode === 'manual') {
      throw new Error('Plan is configured for manual execution');
    }

    const result = await this.executor.executeOrder(plan);
    return result;
  }

  private evaluateMarketCondition(marketData: TradingPlannerInput['marketData']): string {
    const volatilityLabel = marketData.volatility > 0.6 ? 'high volatility' : marketData.volatility > 0.3 ? 'moderate volatility' : 'low volatility';
    const liquidityLabel = marketData.liquidityScore < 0.4 ? 'low liquidity' : 'sufficient liquidity';
    const sentimentLabel = marketData.newsSentimentScore === undefined ? '' : marketData.newsSentimentScore > 0.2 ? 'positive sentiment' : marketData.newsSentimentScore < -0.2 ? 'negative sentiment' : 'neutral sentiment';
    return [volatilityLabel, liquidityLabel, sentimentLabel].filter(Boolean).join(', ');
  }

  private selectTrendBias(marketData: TradingPlannerInput['marketData']) {
    if (marketData.trendStrength >= 0.35) return 'bullish';
    if (marketData.trendStrength <= -0.35) return 'bearish';
    return 'neutral';
  }

  private selectTimeframe(marketData: TradingPlannerInput['marketData'], options: PlannerOptions) {
    if (options.preferredTimeframe) {
      return {
        timeframe: options.preferredTimeframe,
        rationale: `Preferred timeframe ${options.preferredTimeframe} applied`,
      };
    }

    if (marketData.volatility > 0.7) {
      return {
        timeframe: '15m',
        rationale: 'High volatility favors shorter timeframes for tighter control',
      };
    }

    if (marketData.liquidityScore < 0.4) {
      return {
        timeframe: '1h',
        rationale: 'Reduced liquidity suggests a medium-term timeframe to avoid price impact',
      };
    }

    return {
      timeframe: '4h',
      rationale: 'Balanced market conditions support a mid-term trading horizon',
    };
  }

  private selectStrategy(marketData: TradingPlannerInput['marketData'], options: PlannerOptions, marketCondition: string) {
    let name = 'balanced momentum';
    let explanation = 'Default balanced momentum strategy.';
    let category = 'momentum';

    if (options.strategyBias === 'trend' || marketData.trendStrength > 0.5) {
      name = 'trend following';
      explanation = 'Prefer trend-following strategy based on strong directional momentum.';
      category = 'trend';
    } else if (options.strategyBias === 'mean_reversion' || marketData.trendStrength < -0.2) {
      name = 'mean reversion';
      explanation = 'Prefer mean reversion due to neutral or fading trend conditions.';
      category = 'mean_reversion';
    } else if (options.strategyBias === 'breakout' && marketData.price !== undefined) {
      name = 'breakout capture';
      explanation = 'Seek breakout entries from significant support and resistance bands.';
      category = 'breakout';
    }

    if (marketData.volatility > 0.7 && name === 'balanced momentum') {
      name = 'volatility breakout';
      explanation = 'High volatility lends itself to breakout and momentum strategies.';
      category = 'breakout';
    }

    return { name, explanation, category };
  }

  private selectRisk(options: PlannerOptions, marketCondition: string, trendBias: string) {
    const profile = options.riskTolerance ?? 'moderate';
    const baseRisk = options.maxRiskPerTrade ?? 0.02;
    let maxRiskPercent = baseRisk;

    if (profile === 'conservative') {
      maxRiskPercent *= 0.75;
    } else if (profile === 'aggressive') {
      maxRiskPercent *= 1.4;
    }

    if (marketCondition.includes('high volatility')) {
      maxRiskPercent *= 0.8;
    }

    if (trendBias === 'bearish') {
      maxRiskPercent *= 0.9;
    }

    return {
      profile,
      maxRiskPercent: Number(Math.min(maxRiskPercent, 0.1).toFixed(4)),
      rationale: `Risk profile ${profile} with a base risk of ${baseRisk * 100}% per trade. Market condition and bias adjusted risk to ${Number(Math.min(maxRiskPercent, 0.1) * 100).toFixed(2)}%.`,
    };
  }

  private generatePriceTargets(marketData: TradingPlannerInput['marketData'], strategy: any, risk: any, timeframe: any) {
    const entry = marketData.price;
    const buffer = marketData.trendStrength >= 0 ? 0.0025 : -0.0025;
    const stopLossDistance = Math.max(0.01, marketData.volatility * 0.03);
    const takeProfitDistance = stopLossDistance * (strategy.category === 'trend' ? 2.5 : 1.8);

    const stopLoss = Number((entry * (1 - Math.sign(buffer) * stopLossDistance)).toFixed(4));
    const takeProfit = Number((entry * (1 + Math.sign(buffer) * takeProfitDistance)).toFixed(4));
    const riskRewardRatio = Number((takeProfitDistance / stopLossDistance).toFixed(2));

    return {
      entry: Number(entry.toFixed(4)),
      stopLoss: Math.max(0, stopLoss),
      takeProfit: Number(takeProfit.toFixed(4)),
      riskRewardRatio: Number(riskRewardRatio.toFixed(2)),
    };
  }

  private estimateProbability(marketData: TradingPlannerInput['marketData'], strategy: any, risk: any, priceTargets: any) {
    const baseProbability = 0.5 + marketData.trendStrength * 0.2 + (marketData.newsSentimentScore ?? 0) * 0.15;
    const volatilityPenalty = marketData.volatility * 0.1;
    const probability = Math.max(0.1, Math.min(0.9, baseProbability - volatilityPenalty));

    const expectedReturn = Number(((priceTargets.takeProfit - priceTargets.entry) / priceTargets.entry * 100).toFixed(2));
    const expectedLoss = Number(((priceTargets.entry - priceTargets.stopLoss) / priceTargets.entry * 100).toFixed(2));

    return {
      probability: Number(probability.toFixed(3)),
      expectedReturn,
      expectedLoss,
    };
  }

  private calculatePositionSizing(capital: number, risk: any, priceTargets: any, probability: any, options: PlannerOptions) {
    const maxRiskCapital = capital * (risk.maxRiskPercent ?? 0.02);
    const stopLossDistance = Math.abs(priceTargets.entry - priceTargets.stopLoss);
    const quantity = stopLossDistance > 0 ? Math.floor(maxRiskCapital / stopLossDistance) : 0;
    const capitalAllocated = Number(Math.min(capital, quantity * priceTargets.entry).toFixed(2));
    const sizePercent = capitalAllocated > 0 ? Number((capitalAllocated / capital * 100).toFixed(2)) : 0;

    return {
      sizePercent,
      quantity,
      capitalAllocated,
      rationale: `Allocated ${sizePercent}% of capital using ${risk.maxRiskPercent * 100}% risk per trade and stop loss distance of ${stopLossDistance.toFixed(4)}.`,
    };
  }

  private buildExecutionPlan(priceTargets: any, options: PlannerOptions) {
    const orderType = options.executionMode === 'automatic' ? 'limit' : 'market';
    const approvalRequired = options.manualApproval ?? true;

    return {
      orderType,
      executionMode: options.executionMode ?? 'manual',
      approvalRequired,
      brokerInstruction: `Place a ${orderType} order at ${priceTargets.entry} with SL ${priceTargets.stopLoss} and TP ${priceTargets.takeProfit}.`,
      scheduledAt: options.executionMode === 'automatic' ? Date.now() + 1000 * 10 : undefined,
    };
  }
}
