[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "cd trading-bot && python3 -m venv .venv",
    "cd trading-bot && .venv/bin/pip install --upgrade pip",
    "cd trading-bot && .venv/bin/pip install -r requirements.txt"
]

# Kosongkan build phase agar nixpacks tidak auto-detect pnpm build
[phases.build]
cmds = []

[start]
cmd = "cd trading-bot && .venv/bin/python3 main.py"
